site_name: DataLakehouse Study
site_description: Apache Spark com Delta Lake e Apache Iceberg
site_url: https://GabrielNM12.github.io/datalakehouse-study
repo_url: https://github.com/GabrielNM12/datalakehouse-study
repo_name: GabrielNM12/datalakehouse-study

theme:
  name: material
  language: pt
  palette:
    - scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - toc.integrate

nav:
  - Home: index.md
  - Apache Spark: spark.md
  - Delta Lake: delta.md
  - Apache Iceberg: iceberg.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
